default:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: TRANSFORMER
      user: DBT_USER
      warehouse: DBT_WH
      database: ANALYTICS
      schema: PUBLIC
      threads: 8

    prod:
      type: snowflake
      role: TRANSFORMER
      user: DBT_USER
      warehouse: DBT_WH
      database: PRODUCTION
      schema: PUBLIC
      threads: 8
